add_ox_quiz(1, "Los Ninjas Arqueros tienen que comprar flechas en Metin2 Lamda", false)
add_ox_quiz(1, "El vendedor de mazmorras craftea el: Añadir cuarto de slot al arma", true)
add_ox_quiz(1, "La poción refinada grande incrementa el porcentaje de mejora Un 20%", false)
add_ox_quiz(1, "Las botas del vendedor de mazmorras son rojas", false)
add_ox_quiz(1, "El Oso hambriento, puede levantarse en dos patas", true)
add_ox_quiz(1, "La barba del pescador es de color negro", false)
add_ox_quiz(1, "El capitán de ciy, sostiene un cuchillo en una de sus manos", false)
add_ox_quiz(1, "Segun Soon, si una mujer lleva un collar hecho de flor kaki tendrá un hijo", true)
add_ox_quiz(1, "El vendedor de armaduras vende cascos", false)
add_ox_quiz(1, "La lanza del guardaespaldas de city es igual de alta a él", false)
add_ox_quiz(1, "Yonah sostiene un jarrón blanco con dibujos de flores negras", true)
add_ox_quiz(1, "La vendedora de la tienda general vende rocíos", false)
add_ox_quiz(1, "Aranyo es la ex-esposa de Soon ", false)
add_ox_quiz(1, "¿El herrero tiene una espada filosa en lugar de su pie derecho?", true)
add_ox_quiz(1, "¿Baek-go es doctor?", true)
add_ox_quiz(1, "¿El pescador vende un kit de pesca por 4 millomes de Yang?", false)
add_ox_quiz(1, "El papiro de Alejandría sirve para entrar a la mazmorra de Alejandría", false)
add_ox_quiz(1, "¿El metin de Celos es de nivel 40?", false)
add_ox_quiz(1, "¿Existen seis clases de talismanes?", true)
add_ox_quiz(1, "Las cabezas del jefe orco tienen el mismo peinado", false)
add_ox_quiz(1, "A la entrada de Monte sohan hay un fósil de un dragón", true)
add_ox_quiz(1, "¿Se puede pescar en monte sohan?", true)
add_ox_quiz(1, "El muñeco de práctica tiene una pañoleta verde en la frente", false)
add_ox_quiz(1, "El monje combate vende ítems con puntos de batalla que obtienes en la zona de combate", true)
add_ox_quiz(1, "El vendedor de la tienda de armas vende zapatos", true)
add_ox_quiz(1, "El vendedor de mazmorra tiene un pizarrón con el logo de metin2 lamda", true)
add_ox_quiz(1, "Un won equivale a 100 millones en Metin2 Lamda", true)
add_ox_quiz(1, "El pergamino de la guerra que fabrica el herrero requiere el material mineral de cobre mágico", true)
add_ox_quiz(1, "Para intercambiar libros con Soon se deben presentar 3 libros de habilidad para obtener 1", true)
add_ox_quiz(1, "El NPC del almacen tiene un collar de oro con una gema de color rojo", false)
add_ox_quiz(1, "El muñeco de práctica tiene una pañoleta morada en la frente", true)
add_ox_quiz(1, "El lobo alfa azul es un MOB de nivel 12", false)
add_ox_quiz(1, "¿El pescador vende un kit de pesca por 3 millomes de Yang?", true)
add_ox_quiz(1, "Uriel erudito dice: el conocmiemiento es poder?", true)
add_ox_quiz(1, "El padre de DeokBae decia que, si mezclas la flor de campana de forma correcta, la poción te dará fuerza extra durante un corto periodo de tiempo? ", true)
add_ox_quiz(1, "¿Yu-Rang vende pasteles de Arroz para sobrevivir?", true)
add_ox_quiz(1, "¿Cuando usas el libro Reset de Habilidades (de la tienda general), tus puntos de habilidad se reinician?", false)
add_ox_quiz(1, "¿En los asentamientos del Dragon y Bestial, hay tienda Gaya?", false)
add_ox_quiz(1, "Para crear un gremio tienes que ser mínimo nivel 40 ", true)
add_ox_quiz(1, "¿Es necesario ingresar más de dos personas a las mazmorras de Metin2Lamda?", true)
add_ox_quiz(1, "Si estas haciendo una mision del capitán en grupo y no eres el lider, te cuentan las bajas de la mision", false)