add_ox_quiz(1, "Urano es el octavo planeta del sistema solar", false)
add_ox_quiz(1, "La zona abisal en una clasificación del relieve submarino", true)
add_ox_quiz(1, "El paralelo 0, es también llamado la línea del ecuador", true)
add_ox_quiz(1, "OPEP. Significa Organización política especializada en asuntos de paz? ", false)
add_ox_quiz(1, "El campeon del mundial de futbol del 2018 es Alemania", false)
add_ox_quiz(1, " El numero 1 es un numero Primo? ", false)
add_ox_quiz(1, "Brasil es el país más grande de Latinoamerica", true)
add_ox_quiz(1, "RGB significa Red, Gray, Black. Es la composición del color en términos de intensidad de luz para medio electrónicos", false)
add_ox_quiz(1, "Un Phablet es alguien que ama la tecnología?", false)
add_ox_quiz(1, "El vino, es la bebida alcohólica más antigua del mundo", false)
add_ox_quiz(1, "En dragon ball, goku debe reunir 8 esferas del dragon?", false)
add_ox_quiz(1, "En los vengadores, Iron Man es considerado el primer vengador?", false)
add_ox_quiz(1, "En los vengadores, existen 6 gemas del infinito?", true)
add_ox_quiz(1, "George Lucas, es el director del señor de los anillos?", false)
add_ox_quiz(1, "Farkle, Fergus y Felicia son los hijos de los ogros Shrek y Fiona", true)
add_ox_quiz(1, "En la literatura clásica el autor de la obra la Iliada, es anonimo?  ", false)
add_ox_quiz(1, "Leonardo Da vinci pintó la obra llamada la última cena", true)
add_ox_quiz(1, "El disco musical mas vendido es de la banda inglesa The beatles", false)
add_ox_quiz(1, "El apodo del cantante Elvis Presley, es el Rey de Rock", true)
add_ox_quiz(1, "Brasil es el país más grande del mundo?", false)
add_ox_quiz(1, "la Segunda Guerra Mundial empezó en 1939", true)
add_ox_quiz(1, "El tercer planeta del sistema solar tiene agua potable?", true)
add_ox_quiz(1, "Los premios Grammis, son premios que celebran las mejores peliculas y actores de cada año?", false)
add_ox_quiz(1, "La catedral de Notre Dame se incendio en el 2019", true)
add_ox_quiz(1, "El microscopio es un instrumento que se utiliza para ver los astros, satelites y estrellas que habitan el espacio exterior", false)
add_ox_quiz(1, "La moneda oficial de Estados Unidos es el peso Americano?", false)
add_ox_quiz(1, "Las plantas se alimentan a través de la fotosíntesis ", true)
add_ox_quiz(1, "El triagulo equilatero es un triangulo de tres lados iguales", true)
add_ox_quiz(1, "Un lustro son 50 años?", false)
add_ox_quiz(1, "Los pulpos tienen 3 corazones?", true)
add_ox_quiz(1, "Un hexagono tiene 8 lados", false)

