--[[
Server Files Author : BEST Production
Skype : best_desiqner@hotmail.com
Website : www.bestproduction-projects.com
--]]
events_mgr_text = {}
 
events_mgr_text[0] = {  -- Common Manager - [EN] : 0 > [DE] : 1 > [FR] : 2
						[0] = "Arena Turnuvasi",
						[1] = "Arena Turnuvasi",
						[2] = "Arena Turnuvasi"
}

events_mgr_text[1] = {  -- Common Manager - [EN] : 0 > [DE] : 1 > [FR] : 2
						[0] = "Event zaten aktif.",
						[1] = "Event zaten aktif.",
						[2] = "Event zaten aktif."
}

events_mgr_text[2] = {  -- Common Manager - [EN] : 0 > [DE] : 1 > [FR] : 2
						[0] = "Event baþladý.",
						[1] = "Event baþladý.",
						[2] = "Event baþladý."
}

events_mgr_text[3] = {  -- Common Manager - [EN] : 0 > [DE] : 1 > [FR] : 2
						[0] = "Event zaten kapalý.",
						[1] = "Event zaten kapalý.",
						[2] = "Event zaten kapalý."
}

events_mgr_text[4] = {  -- Common Manager - [EN] : 0 > [DE] : 1 > [FR] : 2
						[0] = "Event kapandý.",
						[1] = "Event kapandý.",
						[2] = "Event kapandý."
}

-- Kingdoms War [EN]: 100
events_mgr_text[100] = {
											[0] = "Arena Savasi",
											[1] = "Baþlat",
											[2] = "Kapat",
											[3] = "Bu kanalda %d bu eventi baþlatamazsýn.",
											[4] = "Kapat.",
											[5] = "Krallýðýnýn gayet güçlü olduðunu düþünüyorum[ENTER]umarým þuana kadar olduðu gibi devam edicek!",
											[6] = "Maalesefki krallýðýn savaþda[ENTER]vatandaþlýk haklarý gibi nedenler.",
											[7] = "Katýl",
											[8] = "Sizi oraya gönderemem[ENTER]son savaþda çok yoruldunuz[ENTER]gidip dinlenmelisiniz!",
											[9] = "Harika seni ýþýnlýyorum!",
											[10] = "Eventi baþlatmadan önce seçenekleri deðiþtirebilirsiniz[ENTER]Ödüller ve seviye sýnýrlarý.[ENTER][ENTER]Eðer ayarlamalarý yapmazsanýz event son ayarlarla baþlar[ENTER]Ayarlar.[ENTER][ENTER]Yapýlandýrmak istiyor musun?",
											[11] = "Evet",
											[12] = "Hayýr",
											[13] = "Katýlabilmek için en az %d seviyesinde olman gerekiyor.",
											[14] = "Katýlabilecek en yüksek seviye: %d.",
											[15] = "NOT:Sýnýr koymak istemiyorsanýz 0 yazýn[ENTER]Savaþa girebilecek en düþük leveli girin:",
											[16] = "NOT:Sýnýr koymak istemiyorsanýz 0 yazýn.[ENTER]Savaþa girebilecek en yüksek leveli girin:",
											[17] = "Geçersiz bir deðer girdiniz tekrar deneyin.",
											[18] = "Event ayarlarý kaydedildi.",
											[19] = "Event ayarlarý kontrol edilirken bir hata oluþdu.",
											[20] = "Ödülleri ve limitleri gözden geçerin:",
											[21] = "- En düþük level: %d.",
											[22] = "- En düþük level: Limitsiz.",
											[23] = "- En Yüksek level: %d.",
											[24] = "- En Yüksek level: Limitsiz.",
											[25] = "Etkinliði bu ödüller ve limitler ile açmak istiyor musun?",
											[26] = "NOT: Olmasýný istemiyorsanýz[ENTER]YANG ÖDÜLÜ, 0 yazýn.[ENTER]Yang deðerini girin:[ENTER][ENTER]ortak ödül kazanan krallýðýn[ENTER]alacaðý ödüller anlamýna gelir.",
											[27] = "NOT: Olmasýný istemiyorsanýz[ENTER]ÝTEM ÖDÜLÜ, 0 yazýn.[ENTER]Ortak ödüller için itemin kodunu yazýn:[ENTER][ENTER]ortak ödül kazanan krallýðýn[ENTER]alacaðý ödüller anlamýna gelir.",
											[28] = "NOT: Olmasýný istemiyorsanýz[ENTER]ÝTEM ÖDÜLÜ ADETÝ, 0 yazýn.[ENTER]Ortak ödüllerin adetini girin:[ENTER][ENTER]ortak ödül kazanan krallýðýn[ENTER]alacaðý ödüller anlamýna gelir.",
											[29] = "NOT: Olmasýný istemiyorsanýz[ENTER]YANG ÖDÜLÜ, 0 yazýn.[ENTER]Yangýn en büyük deðerini yazýn:[ENTER][ENTER]ortak ödül kazanan krallýðýn[ENTER]alacaðý ödüller anlamýna gelir.",
											[30] = "NOT: Olmasýný istemiyorsanýz[ENTER]ÝTEM ÖDÜLÜ, 0 yazýn.[ENTER]Ýtemlerin üst deðerini ekleyin:[ENTER][ENTER]ortak ödül kazanan krallýðýn[ENTER]alacaðý ödüller anlamýna gelir.",
											[31] = "NOT: Olmasýný istemiyorsanýz[ENTER]ÝTEM ÖDÜLÜ, 0 yazýn.[ENTER]Ýtemlerin en fazla adeti için deðer ekleyin:[ENTER][ENTER]ortak ödül kazanan krallýðýn[ENTER]alacaðý ödüller anlamýna gelir.",
											[32] = "- Ortak yang ödülü: %d.",
											[33] = "- Ortak yang ödülü: yok.",
											[34] = "- Ortak item ödülü: x%d %s.",
											[35] = "- Ortak item ödülü: yok.",
											[36] = "- En iyi yang ödülü: %d.",
											[37] = "- En iyi yang ödülü: yok.",
											[38] = "- En iyi item ödülü: x%d %s.",
											[39] = "- En iyi item ödülü: yok.",
											[40] = "Bu item kodu yok.",
											[41] = "Savaþtasýn savaþmaný öneririm[ENTER]benimle konuþmakdan daha yararlý olablirsin!",
											[42] = "Ödüller",
											[43] = "Savaþtan ayrýl",
											[44] = "Kralýnýz savaþda[ENTER]baþarýlý olursa ödüllendirilirsiniz.[ENTER][ENTER]",
											[45] = "- Ortak ödül katýlýmcýlarýn ödülünü ifade eder[ENTER]kazanan krallýklar alýcak.[ENTER]- En yüksek ödül katýlýmcýlarýn ödülü anlamýna gelir[ENTER]Kazanan krallýkdaki en yüksek öldürmeye sahip olan[ENTER]alacak.",
											[46] = "Krallýðýnýz savaþý kazanýrsa krallaýðýnýzýn ödülleri[ENTER]þu þekilde artacakdýr:",
											[47] = "- item düþürme oraný: %d%% geçerlilik: %d saat.",
											[48] = "- yang düþürme ornaý: %d%% geçerlilik %d saat.",
											[49] = "- düþürme x10 yang oraný: %d%% geçerlilik %d saat.",
											[50] = "- exp kazanma þansý: %d%% geçerlilik %d saat.",
											[51] = "Ödül yok.",
											[52] = "Savaþý terketmek istiyor musun?[ENTER][ENTER]NOT:Eðer savaþý býrakýrsan geri gelemezsin,[ENTER]Krallýðýnýz sizin tarafýnýzdan yapýlan öldürmeleri kaybedcek[ENTER]ve kazanýrlarsa ödülleri alamayacaksýn.",
											[53] = "Krallýðýnýn þehrine ýþýnlýyorsun",
											[54] = "Bir kaç saniye içinde tekrar deneyin",
											[55] = "Bilgi",
											[56] = "- Savaþýn süresi %d dakika.",
											[57] = "- Eðer bir krallýk %d öldürme oranýna ulaþýrsa kazanacak.",
											[58] = "- Eðer %d sürede çok fazla ölürsen[ENTER]þehrine geri ýþýnlanýrsýn[ENTER]ve krallýðýn savaþý kazanýrsa ödüllerden sende yararlanýrsýn."
}

-- Kingdoms War [DE]: 101
events_mgr_text[101] = {
											[0] = "War between Kingdoms",
											[1] = "Start",
											[2] = "Close",
											[3] = "You need to be on CH %d to can manage the event.",
											[4] = "Stop",
											[5] = "Seem that the kingdoms get along pretty well, so[ENTER]hopefully will it continue like until now!",
											[6] = "Unfortunately your kingdom is in war, for various[ENTER]reasons such as citizens rights.",
											[7] = "Partecipate",
											[8] = "I can't leave you go fighting, you was affected[ENTER]too much in the your last participation, go[ENTER]and rest!",
											[9] = "Great, I will teleport you!",
											[10] = "Before start the event you can config the event[ENTER]rewards and level limits.[ENTER][ENTER]NOTE! IF YOU DON'T CONFIG, EVENT WILL START WITH LAST[ENTER]CONFIGS.[ENTER][ENTER]Do you want to config?",
											[11] = "Yes",
											[12] = "No",
											[13] = "You need to be at least level %d to can partecipate.",
											[14] = "The maximum level to can partecipate is %d.",
											[15] = "NOTE: IF YOU WANT TO DON'T HAVE A LIMIT, INSERT 0.[ENTER]Insert the minimum level to can partecipate at the war:",
											[16] = "NOTE: IF YOU WANT TO DON'T HAVE A LIMIT, INSERT 0.[ENTER]Insert the maximum level to can partecipate at the war:",
											[17] = "You insert a invalid value, try again.",
											[18] = "The event configs was saved.",
											[19] = "The event configs was not saved, there are a error.",
											[20] = "Review of rewards & limits:",
											[21] = "- Minimum level: %d.",
											[22] = "- Minimum level: without limit.",
											[23] = "- Maximum level: %d.",
											[24] = "- Maximum level: without limit.",
											[25] = "Do you want to open the event with this rewards[ENTER]and limits?",
											[26] = "NOTE: IF YOU WANT TO DON'T HAVE COMMON[ENTER]YANG REWARD, INSERT 0.[ENTER]Insert the value for common reward of yang:[ENTER][ENTER]Common reward mean the reward which partecipants[ENTER]from the winner kingdom will receive.",
											[27] = "NOTE: IF YOU WANT TO DON'T HAVE COMMON[ENTER]ITEM REWARD, INSERT 0.[ENTER]Insert the item vnum for common reward of items:[ENTER][ENTER]Common reward mean the reward which partecipants[ENTER]from the winner kingdom will receive.",
											[28] = "NOTE: IF YOU WANT TO DON'T HAVE COMMON[ENTER]ITEM REWARD, INSERT 0.[ENTER]Insert the item count for common reward of items:[ENTER][ENTER]Common reward mean the reward which partecipants[ENTER]from the winner kingdom will receive.",
											[29] = "NOTE: IF YOU WANT TO DON'T HAVE TOP[ENTER]YANG REWARD, INSERT 0.[ENTER]Insert the value for top reward of yang:[ENTER][ENTER]Top reward mean the reward which partecipant[ENTER]from the winner kingdom with biggest count of kill[ENTER]will receive.",
											[30] = "NOTE: IF YOU WANT TO DON'T HAVE TOP[ENTER]ITEM REWARD, INSERT 0.[ENTER]Insert the item vnum for top reward of items:[ENTER][ENTER]Top reward mean the reward which partecipant[ENTER]from the winner kingdom with biggest count of kill[ENTER]will receive.",
											[31] = "NOTE: IF YOU WANT TO DON'T HAVE TOP[ENTER]ITEM REWARD, INSERT 0.[ENTER]Insert the item count for top reward of items:[ENTER][ENTER]Top reward mean the reward which partecipant[ENTER]from the winner kingdom with biggest count of kill[ENTER]will receive.",
											[32] = "- Common yang reward: %d.",
											[33] = "- Common yang reward: no.",
											[34] = "- Common item reward: x%d %s.",
											[35] = "- Common item reward: no.",
											[36] = "- Top yang reward: %d.",
											[37] = "- Top yang reward: no.",
											[38] = "- Top item reward: x%d %s.",
											[39] = "- Top item reward: no.",
											[40] = "This item vnum don't exist.",
											[41] = "You're in war I recommend you to fight instead[ENTER]talking to me!",
											[42] = "Rewards",
											[43] = "Leave the war",
											[44] = "You will be rewarded just if your kingdom will[ENTER]win the war.[ENTER][ENTER]",
											[45] = "- Common reward mean the reward which partecipants[ENTER]from the winner kingdom will receive.[ENTER]- Top reward mean the reward which partecipant[ENTER]from the winner kingdom with biggest count of kill[ENTER]will receive.",
											[46] = "If your kingdom win the war, rates of kingdom[ENTER]will increase by:",
											[47] = "- drop item rate: %d%% for %d hours.",
											[48] = "- drop yang rate: %d%% for %d hours.",
											[49] = "- drop x10 yang rate: %d%% for %d hours.",
											[50] = "- drop exp rate: %d%% for %d hours.",
											[51] = "There are no rewards.",
											[52] = "Do you want to leave the war?[ENTER][ENTER]NOTE: If you choose to leave you can't come back,[ENTER]your kingdom will lose the kills maked by you[ENTER]and also if your kingdom win you will not[ENTER]receive the common reward.",
											[53] = "You will be teleported to our kingdom city...",
											[54] = "Try again in few seconds!",
											[55] = "Informations",
											[56] = "- The war have a time limit of %d minutes.",
											[57] = "- If a kingdom reach %d kills win the war.",
											[58] = "- If you go to be killed %d times you will be teleported[ENTER]back to your kingdom city. If your kingdom win[ENTER]the war, you will also receive the common reward."
}

-- Kingdoms War [FR]: 102
events_mgr_text[102] = {
											[0] = "War between Kingdoms",
											[1] = "Start",
											[2] = "Close",
											[3] = "You need to be on CH %d to can manage the event.",
											[4] = "Stop",
											[5] = "Seem that the kingdoms get along pretty well, so[ENTER]hopefully will it continue like until now!",
											[6] = "Unfortunately your kingdom is in war, for various[ENTER]reasons such as citizens rights.",
											[7] = "Partecipate",
											[8] = "I can't leave you go fighting, you was affected[ENTER]too much in the your last participation, go[ENTER]and rest!",
											[9] = "Great, I will teleport you!",
											[10] = "Before start the event you can config the event[ENTER]rewards and level limits.[ENTER][ENTER]NOTE! IF YOU DON'T CONFIG, EVENT WILL START WITH LAST[ENTER]CONFIGS.[ENTER][ENTER]Do you want to config?",
											[11] = "Yes",
											[12] = "No",
											[13] = "You need to be at least level %d to can partecipate.",
											[14] = "The maximum level to can partecipate is %d.",
											[15] = "NOTE: IF YOU WANT TO DON'T HAVE A LIMIT, INSERT 0.[ENTER]Insert the minimum level to can partecipate at the war:",
											[16] = "NOTE: IF YOU WANT TO DON'T HAVE A LIMIT, INSERT 0.[ENTER]Insert the maximum level to can partecipate at the war:",
											[17] = "You insert a invalid value, try again.",
											[18] = "The event configs was saved.",
											[19] = "The event configs was not saved, there are a error.",
											[20] = "Review of rewards & limits:",
											[21] = "- Minimum level: %d.",
											[22] = "- Minimum level: without limit.",
											[23] = "- Maximum level: %d.",
											[24] = "- Maximum level: without limit.",
											[25] = "Do you want to open the event with this rewards[ENTER]and limits?",
											[26] = "NOTE: IF YOU WANT TO DON'T HAVE COMMON[ENTER]YANG REWARD, INSERT 0.[ENTER]Insert the value for common reward of yang:[ENTER][ENTER]Common reward mean the reward which partecipants[ENTER]from the winner kingdom will receive.",
											[27] = "NOTE: IF YOU WANT TO DON'T HAVE COMMON[ENTER]ITEM REWARD, INSERT 0.[ENTER]Insert the item vnum for common reward of items:[ENTER][ENTER]Common reward mean the reward which partecipants[ENTER]from the winner kingdom will receive.",
											[28] = "NOTE: IF YOU WANT TO DON'T HAVE COMMON[ENTER]ITEM REWARD, INSERT 0.[ENTER]Insert the item count for common reward of items:[ENTER][ENTER]Common reward mean the reward which partecipants[ENTER]from the winner kingdom will receive.",
											[29] = "NOTE: IF YOU WANT TO DON'T HAVE TOP[ENTER]YANG REWARD, INSERT 0.[ENTER]Insert the value for top reward of yang:[ENTER][ENTER]Top reward mean the reward which partecipant[ENTER]from the winner kingdom with biggest count of kill[ENTER]will receive.",
											[30] = "NOTE: IF YOU WANT TO DON'T HAVE TOP[ENTER]ITEM REWARD, INSERT 0.[ENTER]Insert the item vnum for top reward of items:[ENTER][ENTER]Top reward mean the reward which partecipant[ENTER]from the winner kingdom with biggest count of kill[ENTER]will receive.",
											[31] = "NOTE: IF YOU WANT TO DON'T HAVE TOP[ENTER]ITEM REWARD, INSERT 0.[ENTER]Insert the item count for top reward of items:[ENTER][ENTER]Top reward mean the reward which partecipant[ENTER]from the winner kingdom with biggest count of kill[ENTER]will receive.",
											[32] = "- Common yang reward: %d.",
											[33] = "- Common yang reward: no.",
											[34] = "- Common item reward: x%d %s.",
											[35] = "- Common item reward: no.",
											[36] = "- Top yang reward: %d.",
											[37] = "- Top yang reward: no.",
											[38] = "- Top item reward: x%d %s.",
											[39] = "- Top item reward: no.",
											[40] = "This item vnum don't exist.",
											[41] = "You're in war I recommend you to fight instead[ENTER]talking to me!",
											[42] = "Rewards",
											[43] = "Leave the war",
											[44] = "You will be rewarded just if your kingdom will[ENTER]win the war.[ENTER][ENTER]",
											[45] = "- Common reward mean the reward which partecipants[ENTER]from the winner kingdom will receive.[ENTER]- Top reward mean the reward which partecipant[ENTER]from the winner kingdom with biggest count of kill[ENTER]will receive.",
											[46] = "If your kingdom win the war, rates of kingdom[ENTER]will increase by:",
											[47] = "- drop item rate: %d%% for %d hours.",
											[48] = "- drop yang rate: %d%% for %d hours.",
											[49] = "- drop x10 yang rate: %d%% for %d hours.",
											[50] = "- drop exp rate: %d%% for %d hours.",
											[51] = "There are no rewards.",
											[52] = "Do you want to leave the war?[ENTER][ENTER]NOTE: If you choose to leave you can't come back,[ENTER]your kingdom will lose the kills maked by you[ENTER]and also if your kingdom win you will not[ENTER]receive the common reward.",
											[53] = "You will be teleported to our kingdom city...",
											[54] = "Try again in few seconds!",
											[55] = "Informations",
											[56] = "- The war have a time limit of %d minutes.",
											[57] = "- If a kingdom reach %d kills win the war.",
											[58] = "- If you go to be killed %d times you will be teleported[ENTER]back to your kingdom city. If your kingdom win[ENTER]the war, you will also receive the common reward."
}