quest TrashTalk begin
	state start begin
		when 20091.chat."Nuevo Entendimiento" begin
			raw_script("[TEXT_HORIZONTAL_ALIGN_CENTER]")
			say_yellow("~Seon-Pyeon~")
			say("Amigo mio, el mundo esta lleno de preguntas")
			say("sin resolver Y yo, soy un buscador de respuestas")
			say("y un buscador de conocimiento.")
			say("¿Has oido alguna vez sobre armas epicas y")
			say("Piedras Espiritu?")
			say("")
		end
		when 20091.chat."¿Que estas Haciendo?" begin
			raw_script("[TEXT_HORIZONTAL_ALIGN_CENTER]")
			say_yellow("~Seon-Pyeon~")
			say("Posiblemente ya sepas que investigo lo")
			say("desconocido y actualmente estoy examinando")
			say("un metodo adicional de reforzar armas y mejorar")
			say("el poder de las Piedras Espiritu.")
			say("")
		end
		when 20091.chat."La Investigacion de las Armas" begin
			raw_script("[TEXT_HORIZONTAL_ALIGN_CENTER]")
			say_yellow("~Seon-Pyeon~")
			say("Interesante, ¿no? ¿Quieres saber mas sobre esto?")
			say("Entonces traeme el Arma +9 de Nivel 65 ")
			say("y los objetos necesarios, con eso sera suficiente")
			say("para crear un arma epica.")
			say("la mejora tiene 100% de exito.")
			say("")
			end
		when 20008.chat."Mmm,huele bien Aqui!" begin
			raw_script("[TEXT_HORIZONTAL_ALIGN_CENTER]")
			say_yellow("~Octavio~")
			say("¡Bienvenido! Nuestro restaurante es parte de una")
			say("enorme cadena internacional. Entra y pruebalo.")
			say("El local es amplio y bonito sin embargo")
			say("tiene una decoracion muy simple.")
			say("")
		end
		when 20017.chat."Ve, Dilo en la Montaña" begin
			raw_script("[TEXT_HORIZONTAL_ALIGN_CENTER]")
			say_yellow("~Yu-Whan~")
			say("...Sobre las colinas y en todas partes...")
			say("¿Tambien te gusta la musica? Canto todo tipo de")
			say("canciones aqui en la soledad, asi no me involucro")
			say("en la guerra. Pero sin un pais que me proteja,")
			say("no podre seguir haciendo lo que hago.")
			say("")
		end
		when 20023.chat."¿Por que lees Tanto?" begin
			raw_script("[TEXT_HORIZONTAL_ALIGN_CENTER]")
			say_yellow("~Soon~")
			say("Oh, aventurero. El mundo esta lleno de problemas")
			say("y solo a traves de la sabiduria puedes")
			say("sobrevivir. Honra siempre tus libros. Te ayudaran")
			say("en los malos momentos. ¡Creeme!")
			say("")
		end
			when 20023.chat."¿Tienes hijos?" begin
			raw_script("[TEXT_HORIZONTAL_ALIGN_CENTER]")
			say_yellow("~Soon~")
			say("En realidad no queria hijos,pero...")
			say("Bueno, sigo recogiendo Flores Kaki por que si las")
			say("preparas correctamente, puedes intensificar tu")
			say("energia magica con ellas. Lo descubrio Baek-Go.")
			say("Solo necesita una flor para hacer 100 pociones.")
			say("Por desgracia, la Flor Kaki tambien tiene un")
			say("efecto secundario. Si una mujer lleva un collar")
			say("hecho de esta flor, tendra un hijo. Entre tu y")
			say("yo, mi mujer saco provecho de esto")
			say("descaradamente.")
			say("")
		end
		when 20020.chat."¿Por que tanta gente te llama traidor?" begin
			raw_script("[TEXT_HORIZONTAL_ALIGN_CENTER]")
			say_yellow("~Balso~")
			say("Escape de la guerra y me uni al Clan del viento")
			say("Negro. Mis camaradas nunca me perdonaron por eso.")
			say("Despues descubri que los Guerreros del viento")
			say("Negro mataban a gente inocente, asi que les deje")
			say("inmediatamente. ¡Era horrible!")
			say("")
			wait()
			say_yellow("~Balso~")
			say("¿Tienes gente inocente en la conciencia? Entonces")
			say("verdaderamente te mereces tu nombre. Les")
			say("impediste protagonizar una buena vida.")
			say("")
			wait()
			say_yellow("~Balso~")
			say("Vivimos en un mundo sin ley. Pero he decidido que")
			say("no hare ningun mal nunca mas. No quiero que la")
			say("gente siga describiendome como un traidor.")
			say("")
			say("¿Tienes algo de Yang para mi?")
			say("")
		end
		when 20011.chat."¿Te llaman el Erudito?" begin
			raw_script("[TEXT_HORIZONTAL_ALIGN_CENTER]")
			say_yellow("~Uriel~")
			say("Hay tantas cosas que aprender en este vasto")
			say("mundo. La ignorancia sumada al poder militar son")
			say("una mala combinacion. Tu no quieres vivir como")
			say("esos soldados ignorantes, ¿no? ¡El conocimiento")
			say("es el poder!")
			say("")
		end
		when 20018.chat."¿Mis fuentes me dicen que practicas Medicina?" begin
			raw_script("[TEXT_HORIZONTAL_ALIGN_CENTER]")
			say_yellow("~Baek-Go~")
			say("Hago lo que puedo. Pero hay mas y mas accidentes")
			say("cada dia en este mundo peligroso. No tenemos")
			say("suficientes medicinas ni ayudantes. ¡Los tiempos")
			say("son dificiles! Quiza puedas echarme una mano mas")
			say("tarde?")
			say("")
		end
		when 20019.chat."¿Como va la Caza?" begin
			raw_script("[TEXT_HORIZONTAL_ALIGN_CENTER]")
			say_yellow("~Yang-Shin~")
			say("Hmm, desde que las piedras Metin cayeron, los")
			say("animales se han vuelto realmente salvajes. Hoy en")
			say("dia, ya arriesgas tu vida saliendo a cazar")
			say("algunos pollos. Son tiempos peligrosos para los")
			say("cazadores.Por suerte, ¡soy uno de los mejores!")
			say("")
		end
		when 20003.chat."¿Como Estas?" begin
			raw_script("[TEXT_HORIZONTAL_ALIGN_CENTER]")
			say_yellow("~Ah-Yu~")
			say("¡Mi niño Ugh. Ahora que mi marido ha caido en la")
			say("guerra, tengo que cuidar de mi misma. Trado de")
			say("mantenerme a mi y a mi bebe por mi cuenta. Con el")
			say("agua Bo, encontre la posibilidad de mejorar mi")
			say("vida. Tengo que darle a Yu-Hwan 100 jugos de flor")
			say("kaki y una seta Tue. De esto, el elabora agua Bo,")
			say("que puedo vender realmente facil. Despues de todo")
			say("la necesito para sobrevivir de alguna manera...")
			say("")
		end
		when 20006.chat."¿Donde esta tu Hermano?" begin
			raw_script("[TEXT_HORIZONTAL_ALIGN_CENTER]")
			say_yellow("~Mirine~")
			say("Últimamente mi hermano ha estado viajando mucho.")
			say("Escasamente le veo y me preocupo mucho por el.")
			say("")
			wait()
			say_yellow("~Mirine~")
			say("Solia recoger Flores Melocoton con mi hermano.")
			say("Pero ahora tengo que hacerlo todo sola. No son")
			say("muy bonitas, pero tienen un efecto especial. Si")
			say("le llevas una Flor Melocoton a Baek-Go,")
			say("¡preparara una pocion con ella, que te hace muy")
			say("rapido!")
			say("")
		end
		when 20012.chat."¿Vendes Pasteles de Arroz?" begin
			raw_script("[TEXT_HORIZONTAL_ALIGN_CENTER]")
			say_yellow("~Yu-Rang~")
			say("A causa de la guerra, es dificil vender pastel de")
			say("arroz. Gracias a los bandidos, he perdido muchos")
			say("clientes. Ya no se que debo hacer para")
			say("sobrevivir.")
			say("")
		end
		when 20021.chat."Guerra en el Reino Seungryong" begin
			raw_script("[TEXT_HORIZONTAL_ALIGN_CENTER]")
			say_yellow("~Ariyoung~")
			say("Estamos perdiendo mas y mas hombres durante")
			say("la guerra, asi que las mujeres de la aldea se")
			say("juntaron y le dieron a Huahn-So que crease una")
			say("pocion curativa mejor. Despues de una larga")
			say("investigacion, produjo una pocion que aumenta la")
			say("defensa, para asi tener que usar menos pociones")
			say("curativas. Ve a verle. Seguro que puede hacer")
			say("para ti la pocion,que el llama Agua SamBo. Solo")
			say("necesita algo de Agua Dok y una Rosa Alpina para")
			say("hacerla.")
			say("")
		end
		when 20021.chat."¿Por que estas tan Triste?" begin
			raw_script("[TEXT_HORIZONTAL_ALIGN_CENTER]")
			say_yellow("~Ariyoung~")
			say("Oh, quien podria haber sabido que nuestros dulces")
			say("sueños iban a ser hechos pedazos tan")
			say("despiadadamente... Mi pobre marido, ¡cayo durante")
			say("la batalla!... Por favor, venga su muerte.")
			say("")
		end
		when 20002.chat."¿Como esta tu marido?" begin
			raw_script("[TEXT_HORIZONTAL_ALIGN_CENTER]")
			say_yellow("~Aranyo~")
			say("¿El raton de biblioteca?")
			say("asi llamado mi marido esta casado con sus libros.")
			say("Apenas me mira ya. Y no soy una mujer fea.")
			say("")
		end
		when 20015.chat."Fuerza Heredada" begin
			raw_script("[TEXT_HORIZONTAL_ALIGN_CENTER]")
			say_yellow("~Leñador Deokbae~")
			say("Durante muchos años, el secreto de la fuerza ha")
			say("sido transmitido en nuestra familia. Mi padre me")
			say("dijo que si mezclas la flor campana de forma")
			say("correcta, la pocion te dara fuerza extra durante")
			say("un corto periodo de tiempo. Hasta donde yo se,")
			say("Baek-Go es capaz de preparar esta pocion. Solo")
			say("tienes que llevarle una flor campana.")
			say("")
		end
		when 20014.chat."¿Por que estas de mal Humor?" begin
			raw_script("[TEXT_HORIZONTAL_ALIGN_CENTER]")
			say_yellow("~Taurean~")
			say("¡Harang es una mala chica! ¡La odio! ¡Soy debil y")
			say("me fastidia a menudo!")
			say("")
		end
		when 20024.chat."Taurean el Miedoso" begin
			raw_script("[TEXT_HORIZONTAL_ALIGN_CENTER]")
			say_yellow("~Harang~")
			say("Estoy esperando a Taurean. solemos jugar juntos y")
			say("tambien peleamos mucho. ¡Que cobarde! Si no viene")
			say("voluntariamente,")
			say("¡se lo hare pasar verdaderamente mal!")
			say("")
		end
	end
end
